version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./media:/app/media
      - ./ssl:/app/ssl
    environment:
      - DEBUG=False
      - SECRET_KEY=your-production-secret-key
    restart: unless-stopped